<?php
/**
 * Cybage Customer Group Specific Products Plugin
 *
 * @category   Customer Group Specific Products Plugin
 * @package    Cybage_Customergroup
 * @copyright  Copyright (c) 2015 Cybage Software Pvt. Ltd., India
 *             http://www.cybage.com/coe/e-commerce
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @author     Cybage Software Pvt. Ltd. 
 */
?>

<?php $_options = $this->getSelectedOptions(); ?>
<?php $_assignedGroups = $this->getAssignedGroups(); ?>
<?php if($_options) { ?>
    <?php foreach($_options as $_option) { ?>
        <option value="<?php echo $_option['value']; ?>" <?php if(in_array($_option['value'], $_assignedGroups)) { ?> selected="selected" <?php } ?>><?php echo $_option['label']; ?></option>
    <?php } ?>
<?php } ?>